-- =====================================================================
-- backend/database/school_management.sql
-- School Management SaaS - Database Schema
--
-- NOTE ON THE ADMIN PASSWORD:
-- A bcrypt hash cannot be safely hand-written — it must be generated by
-- bcrypt itself (each run produces a different salt/hash, and a fabricated
-- string would silently fail to log in). Instead of pasting an unverified
-- hash here, run the companion seeder AFTER this SQL file has created the
-- database and tables:
--
--   node backend/database/seed.js
--
-- That script hashes "admin123" with bcrypt and inserts the real admin
-- account safely. This is the correct, production-safe way to seed
-- credentials (never commit real hashes to plain SQL in real projects).
-- =====================================================================

CREATE DATABASE IF NOT EXISTS school_management
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE school_management;

-- ---------------------------------------------------------------------
-- USERS  (system accounts: Admin, Staff, etc.)
-- ---------------------------------------------------------------------
CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('Admin', 'Staff', 'Accountant', 'Teacher') NOT NULL DEFAULT 'Staff',
  profile_image VARCHAR(255) DEFAULT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  last_login DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_users_role (role),
  INDEX idx_users_status (status)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- CLASSES
-- ---------------------------------------------------------------------
CREATE TABLE classes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  class_name VARCHAR(100) NOT NULL,
  section VARCHAR(50) NOT NULL,
  capacity INT UNSIGNED NOT NULL DEFAULT 30,
  class_teacher_id INT UNSIGNED DEFAULT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY uq_class_section (class_name, section),
  INDEX idx_classes_status (status)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- TEACHERS
-- ---------------------------------------------------------------------
CREATE TABLE teachers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  photo VARCHAR(255) DEFAULT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  gender ENUM('Male', 'Female', 'Other') NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  address TEXT,
  qualification VARCHAR(150) DEFAULT NULL,
  experience_years DECIMAL(4,1) DEFAULT 0,
  salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  joining_date DATE NOT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_teachers_status (status),
  INDEX idx_teachers_name (last_name, first_name)
) ENGINE=InnoDB;

-- Now that teachers exists, attach the FK on classes.class_teacher_id
ALTER TABLE classes
  ADD CONSTRAINT fk_classes_teacher
  FOREIGN KEY (class_teacher_id) REFERENCES teachers(id)
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- SUBJECTS
-- ---------------------------------------------------------------------
CREATE TABLE subjects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject_name VARCHAR(150) NOT NULL,
  code VARCHAR(30) NOT NULL UNIQUE,
  teacher_id INT UNSIGNED DEFAULT NULL,
  class_id INT UNSIGNED DEFAULT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_subjects_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_subjects_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_subjects_status (status)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- STUDENTS
-- ---------------------------------------------------------------------
CREATE TABLE students (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  photo VARCHAR(255) DEFAULT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  gender ENUM('Male', 'Female', 'Other') NOT NULL,
  date_of_birth DATE NOT NULL,
  guardian_name VARCHAR(150) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150) DEFAULT NULL,
  address TEXT,
  class_id INT UNSIGNED DEFAULT NULL,
  admission_date DATE NOT NULL,
  status ENUM('Active', 'Inactive', 'Graduated', 'Suspended') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_students_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_students_status (status),
  INDEX idx_students_name (last_name, first_name),
  INDEX idx_students_class (class_id)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- EMPLOYEES (non-teaching staff, paid via the salary module too)
-- ---------------------------------------------------------------------
CREATE TABLE employees (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  photo VARCHAR(255) DEFAULT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  designation VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150) DEFAULT NULL,
  address TEXT,
  salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  joining_date DATE NOT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_employees_status (status)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- SALARIES  (pays either a teacher OR an employee — exactly one)
-- ---------------------------------------------------------------------
CREATE TABLE salaries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT UNSIGNED DEFAULT NULL,
  employee_id INT UNSIGNED DEFAULT NULL,
  amount DECIMAL(12,2) NOT NULL,
  payment_date DATE DEFAULT NULL,
  month TINYINT UNSIGNED NOT NULL,
  year SMALLINT UNSIGNED NOT NULL,
  status ENUM('Pending', 'Paid', 'Cancelled') NOT NULL DEFAULT 'Pending',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_salaries_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_salaries_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_salaries_payee CHECK (
    (teacher_id IS NOT NULL AND employee_id IS NULL) OR
    (teacher_id IS NULL AND employee_id IS NOT NULL)
  ),
  UNIQUE KEY uq_salary_period (teacher_id, employee_id, month, year),
  INDEX idx_salaries_status (status),
  INDEX idx_salaries_period (year, month)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- STUDENT PAYMENTS
-- ---------------------------------------------------------------------
CREATE TABLE student_payments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT UNSIGNED NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  payment_date DATE NOT NULL,
  receipt_number VARCHAR(50) NOT NULL UNIQUE,
  payment_method ENUM('Cash', 'Card', 'Bank Transfer', 'Online') NOT NULL DEFAULT 'Cash',
  description VARCHAR(255) DEFAULT NULL,
  status ENUM('Pending', 'Completed', 'Refunded', 'Cancelled') NOT NULL DEFAULT 'Completed',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_payments_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_payments_status (status),
  INDEX idx_payments_date (payment_date)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- RECEIPTS (issued for a student payment)
-- ---------------------------------------------------------------------
CREATE TABLE receipts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_payment_id INT UNSIGNED NOT NULL,
  receipt_number VARCHAR(50) NOT NULL UNIQUE,
  issued_date DATE NOT NULL,
  issued_by INT UNSIGNED DEFAULT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_receipts_payment FOREIGN KEY (student_payment_id) REFERENCES student_payments(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_receipts_user FOREIGN KEY (issued_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- TRANSACTIONS  (every financial operation logs one row here)
-- ---------------------------------------------------------------------
CREATE TABLE transactions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  reference_number VARCHAR(50) NOT NULL UNIQUE,
  amount DECIMAL(12,2) NOT NULL,
  type ENUM('Salary', 'Student Payment') NOT NULL,
  salary_id INT UNSIGNED DEFAULT NULL,
  student_payment_id INT UNSIGNED DEFAULT NULL,
  transaction_date DATE NOT NULL,
  transaction_time TIME NOT NULL,
  status ENUM('Pending', 'Completed', 'Failed', 'Reversed') NOT NULL DEFAULT 'Completed',
  created_by INT UNSIGNED DEFAULT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_transactions_salary FOREIGN KEY (salary_id) REFERENCES salaries(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_transactions_payment FOREIGN KEY (student_payment_id) REFERENCES student_payments(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_transactions_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_transactions_type (type),
  INDEX idx_transactions_status (status),
  INDEX idx_transactions_date (transaction_date)
) ENGINE=InnoDB;

-- =====================================================================
-- SAMPLE DATA (classes, a teacher, a student — realistic dev fixtures)
-- The admin user is inserted by backend/database/seed.js, NOT here.
-- =====================================================================

INSERT INTO classes (class_name, section, capacity, status) VALUES
  ('Grade 1', 'A', 30, 'Active'),
  ('Grade 2', 'A', 30, 'Active'),
  ('Grade 3', 'A', 28, 'Active');

INSERT INTO teachers (first_name, last_name, gender, phone, email, address, qualification, experience_years, salary, joining_date, status) VALUES
  ('Sarah', 'Johnson', 'Female', '+1-555-0101', 'sarah.johnson@example.com', '123 Maple St', 'M.Ed', 5.5, 4200.00, '2021-08-15', 'Active');

UPDATE classes SET class_teacher_id = 1 WHERE id = 1;

INSERT INTO subjects (subject_name, code, teacher_id, class_id, status) VALUES
  ('Mathematics', 'MATH101', 1, 1, 'Active'),
  ('English', 'ENG101', 1, 1, 'Active');

INSERT INTO students (first_name, last_name, gender, date_of_birth, guardian_name, phone, email, address, class_id, admission_date, status) VALUES
  ('Liam', 'Carter', 'Male', '2016-03-12', 'Emma Carter', '+1-555-0202', 'liam.carter.guardian@example.com', '456 Oak Ave', 1, '2022-09-01', 'Active');

INSERT INTO employees (first_name, last_name, designation, phone, email, address, salary, joining_date, status) VALUES
  ('David', 'Miller', 'Accountant', '+1-555-0303', 'david.miller@example.com', '789 Pine Rd', 3000.00, '2020-01-10', 'Active');
